# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('mobile', models.IntegerField()),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('resume', models.ImageField(default='resume/None/no-img.jpg', upload_to='resume/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
