# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161213_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='resume',
            field=models.FileField(default='resume/None/no-img.jpg', upload_to='resume/'),
        ),
    ]
